# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajanje', models.CharField(max_length=200)),
                ('stroski', models.TextField()),
                ('mail', models.CharField(max_length=200)),
                ('ustvarjeno', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
