# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180321_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajanje', models.CharField(max_length=200)),
                ('stroski', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('ustvarjeno', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
