# Generated by Django 2.0.3 on 2018-04-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odgovori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor1', models.CharField(max_length=200)),
                ('odgovor2', models.CharField(max_length=200)),
                ('odgovor3', models.CharField(max_length=200)),
                ('platforma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vprasanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vprasanje', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='odgovori',
            name='vprasanje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vprasanja'),
        ),
    ]
