# Generated by Django 2.0.3 on 2018-04-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odgovori',
            old_name='vprasanje',
            new_name='vprasanja',
        ),
    ]
