# Generated by Django 2.0.3 on 2018-04-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180403_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odgovori',
            old_name='vprasanja',
            new_name='vprasanje',
        ),
    ]
