# Generated by Django 2.0.3 on 2018-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180403_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='odgovori',
            unique_together={('odgovor1', 'odgovor2')},
        ),
    ]
