# Generated by Django 2.0.3 on 2018-04-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180403_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='odgovori',
            unique_together=set(),
        ),
    ]
