# Generated by Django 2.0.3 on 2018-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180403_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izracun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpr', models.CharField(max_length=200)),
                ('cena', models.IntegerField(default=0)),
            ],
        ),
    ]
