# Generated by Django 2.0.3 on 2018-05-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_izracun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subquestion', models.CharField(blank=True, max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(blank=True, max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vsi', to='api.Feature')),
            ],
        ),
    ]
