# Generated by Django 2.0.3 on 2018-05-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feature_subquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='api.Feature'),
        ),
    ]
