# Generated by Django 2.0.3 on 2018-05-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180513_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Izracun',
        ),
        migrations.RemoveField(
            model_name='odgovori',
            name='vprasanje',
        ),
        migrations.RemoveField(
            model_name='subquestions',
            name='question',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='question',
            new_name='feature_name',
        ),
        migrations.DeleteModel(
            name='Odgovori',
        ),
        migrations.DeleteModel(
            name='SubQuestions',
        ),
        migrations.DeleteModel(
            name='Vprasanja',
        ),
        migrations.AddField(
            model_name='name',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='api.Feature'),
        ),
    ]
