# Generated by Django 2.0.5 on 2018-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_calculate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
