# Generated by Django 2.0.5 on 2018-05-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
