# Generated by Django 2.0.5 on 2018-05-15 14:15

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=500)),
                ('check', models.BooleanField(default=False)),
                ('fk_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='api.Feature')),
            ],
        ),
        migrations.AlterField(
            model_name='name',
            name='time',
            field=models.FloatField(validators=[rest_framework.compat.MinValueValidator(0.5), rest_framework.compat.MaxValueValidator(100)]),
        ),
    ]
