# Generated by Django 2.0.5 on 2018-05-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180515_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fk_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='api.Name'),
        ),
    ]
