# Generated by Django 2.0.5 on 2018-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180515_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
