# Generated by Django 2.0.5 on 2018-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180515_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
