# Generated by Django 2.0.5 on 2018-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180515_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='checked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='check',
            field=models.IntegerField(default=0),
        ),
    ]
