# Generated by Django 2.0.5 on 2018-05-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180515_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='fk_template',
        ),
        migrations.AddField(
            model_name='name',
            name='fk_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='api.Template'),
            preserve_default=False,
        ),
    ]
