# Generated by Django 2.0.5 on 2018-05-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180515_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='fk_template',
        ),
    ]
