# Generated by Django 2.0.4 on 2018-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180516_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
