# Generated by Django 2.0.4 on 2018-05-20 10:43

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_template_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='backend_time',
            field=models.IntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(0), rest_framework.compat.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='frontend_time',
            field=models.IntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(0), rest_framework.compat.MaxValueValidator(99)]),
            preserve_default=False,
        ),
    ]
