# Generated by Django 2.0.4 on 2018-05-21 09:00

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180520_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='backend_time',
        ),
        migrations.RemoveField(
            model_name='name',
            name='frontend_time',
        ),
        migrations.AddField(
            model_name='name',
            name='android_developer',
            field=models.FloatField(default=1, validators=[rest_framework.compat.MinValueValidator(0.5), rest_framework.compat.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='backend_developer',
            field=models.FloatField(default=1, validators=[rest_framework.compat.MinValueValidator(0.5), rest_framework.compat.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='ios_developer',
            field=models.FloatField(default=1, validators=[rest_framework.compat.MinValueValidator(0.5), rest_framework.compat.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
