# Generated by Django 2.0.4 on 2018-05-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180521_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate',
            name='days',
        ),
        migrations.RemoveField(
            model_name='calculate',
            name='price',
        ),
    ]
