# Generated by Django 2.0.4 on 2018-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180522_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='time',
            new_name='total_time',
        ),
        migrations.RemoveField(
            model_name='name',
            name='platform',
        ),
    ]
