# Generated by Django 2.0.3 on 2018-05-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180522_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculate',
        ),
    ]
